import { Poppins, Inter } from "next/font/google";
import "../styles/globals.css";
import MotionLayout from "../ui/organisms/MotionLayaut";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${poppins.variable} ${inter.variable}`}>
      <body className="bg-[#121212] text-white scroll-smooth p-4">
        <MotionLayout>
          {children}
        </MotionLayout>
      </body>
    </html>
  );
}
